apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-name-jenkis
spec:
  selector:
   matchLabels:
    app: my-name-app-jenkis
  replicas: 1
  template:
    metadata:
      labels:
        app: my-name-app-jenkis
    spec:
      containers:
        - name: my-name-app-jenkis
          image: esilfa/my-name:0.0.0.1     
          ports:
            - containerPort: 3000
              name: mynameappport
---
kind: Service
apiVersion: v1
metadata:
  name: my-name-app-jenkins
  labels:
    app: my-name-app-jenkins
spec:   
  ports:
  - name: my-name-app-jenkins
    port: 8081
    nodePort : 30000
  #type: LoadBalancer
  type: NodePort
  selector:
   app: my-name-app-jenkins
